// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qbvhIJ5ipE0lwh6ZWrZF6TJonHW_7Jg',
    appId: '1:1053314522526:android:6f4d88447b4acbbb908a8f',
    messagingSenderId: '1053314522526',
    projectId: 'carmel-bakery-app',
    storageBucket: 'carmel-bakery-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Qc839UmYnM0HCCMqHc86AQKpPufsdcQ',
    appId: '1:1053314522526:ios:855ea1a5aff09ec6908a8f',
    messagingSenderId: '1053314522526',
    projectId: 'carmel-bakery-app',
    storageBucket: 'carmel-bakery-app.appspot.com',
    iosClientId: '1053314522526-smt8qquun17nmdjr093gec2b3i99e1v2.apps.googleusercontent.com',
    iosBundleId: 'com.mateuszsoltys.carmelBakeryy',
  );
}
